package cl.model.pojos;
// Generated 11-dic-2018 11:36:45 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private String duiPaciente;
     private String nombre;
     private String clave;
     private String correo;
     private Set consultas = new HashSet(0);
     private Set recetases = new HashSet(0);

    public Paciente() {
    }

	
    public Paciente(String duiPaciente, String nombre, String clave, String correo) {
        this.duiPaciente = duiPaciente;
        this.nombre = nombre;
        this.clave = clave;
        this.correo = correo;
    }
    public Paciente(String duiPaciente, String nombre, String clave, String correo, Set consultas, Set recetases) {
       this.duiPaciente = duiPaciente;
       this.nombre = nombre;
       this.clave = clave;
       this.correo = correo;
       this.consultas = consultas;
       this.recetases = recetases;
    }
   
    public String getDuiPaciente() {
        return this.duiPaciente;
    }
    
    public void setDuiPaciente(String duiPaciente) {
        this.duiPaciente = duiPaciente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Set getConsultas() {
        return this.consultas;
    }
    
    public void setConsultas(Set consultas) {
        this.consultas = consultas;
    }
    public Set getRecetases() {
        return this.recetases;
    }
    
    public void setRecetases(Set recetases) {
        this.recetases = recetases;
    }




}


